import { Item, Inventory, Station, SupplyRelease, DailyUsage, HistoryRecord } from './db-schema'

export const mockItems: Item[] = [
  {
    id: 1,
    name: 'Surgical Gloves',
    brand: 'Medline',
    sku: 'MED-SG-001',
    cost_price: 0.5,
    selling_price: 1.2,
    expiration_date: '2025-12-31',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 2,
    name: 'Face Mask N95',
    brand: 'Honeywell',
    sku: 'HON-FM-001',
    cost_price: 0.8,
    selling_price: 2.0,
    expiration_date: '2025-11-30',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 3,
    name: 'IV Cannula 18G',
    brand: 'B. Braun',
    sku: 'BBR-IV-018',
    cost_price: 1.5,
    selling_price: 4.5,
    expiration_date: '2026-06-30',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 4,
    name: 'Syringes 10ml',
    brand: 'Terumo',
    sku: 'TER-SYR-10',
    cost_price: 0.3,
    selling_price: 0.8,
    expiration_date: '2026-08-31',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 5,
    name: 'Oxygen Mask',
    brand: 'Vyaire',
    sku: 'VYR-OM-001',
    cost_price: 5.0,
    selling_price: 15.0,
    expiration_date: '2025-10-31',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 6,
    name: 'Gauze Pads 4x4',
    brand: 'Kendall',
    sku: 'KND-GP-44',
    cost_price: 0.2,
    selling_price: 0.6,
    expiration_date: '2026-03-31',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
]

export const mockStations: Station[] = [
  { id: 1, name: 'ER', location: 'Building A, Floor 1' },
  { id: 2, name: 'OB-GYNE', location: 'Building B, Floor 2' },
  { id: 3, name: 'OR', location: 'Building A, Floor 3' },
  { id: 4, name: 'DR', location: 'Building C, Floor 1' },
  { id: 5, name: 'PEDIA', location: 'Building B, Floor 1' },
  { id: 6, name: 'MEDICINE', location: 'Building C, Floor 2' },
  { id: 7, name: 'SURGICAL', location: 'Building A, Floor 4' },
  { id: 8, name: 'OPD', location: 'Building D, Floor 1' },
  { id: 9, name: 'NICU', location: 'Building B, Floor 3' },
]

export const mockInventory: Inventory[] = [
  {
    id: 1,
    item_id: 1,
    quantity: 5000,
    location: 'Central Supply',
    status: 'active',
    last_updated: new Date().toISOString(),
    item: mockItems[0],
  },
  {
    id: 2,
    item_id: 2,
    quantity: 3000,
    location: 'Central Supply',
    status: 'active',
    last_updated: new Date().toISOString(),
    item: mockItems[1],
  },
  {
    id: 3,
    item_id: 3,
    quantity: 1500,
    location: 'Central Supply',
    status: 'active',
    last_updated: new Date().toISOString(),
    item: mockItems[2],
  },
  {
    id: 4,
    item_id: 4,
    quantity: 8000,
    location: 'Central Supply',
    status: 'active',
    last_updated: new Date().toISOString(),
    item: mockItems[3],
  },
  {
    id: 5,
    item_id: 5,
    quantity: 200,
    location: 'Central Supply',
    status: 'active',
    last_updated: new Date().toISOString(),
    item: mockItems[4],
  },
  {
    id: 6,
    item_id: 6,
    quantity: 10000,
    location: 'Central Supply',
    status: 'active',
    last_updated: new Date().toISOString(),
    item: mockItems[5],
  },
]

export const mockSupplyReleases: SupplyRelease[] = [
  {
    id: 1,
    item_id: 1,
    station_id: 1,
    quantity_released: 500,
    quantity_remaining: 4500,
    released_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    released_by: 'Admin User',
    status: 'confirmed',
    item: mockItems[0],
    station: mockStations[0],
  },
  {
    id: 2,
    item_id: 2,
    station_id: 1,
    quantity_released: 300,
    quantity_remaining: 2700,
    released_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    released_by: 'Admin User',
    status: 'confirmed',
    item: mockItems[1],
    station: mockStations[0],
  },
]

export const mockDailyUsages: DailyUsage[] = Array.from({ length: 31 }, (_, day) => ({
  id: day + 1,
  item_id: 1,
  station_id: 1,
  usage_date: new Date(Date.now() - (30 - day) * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  am_quantity: Math.floor(Math.random() * 10),
  pm_quantity: Math.floor(Math.random() * 10),
  quantity_remaining_after: 500 - (day + 1) * 5,
  status: day < 3 ? 'pending' : 'confirmed',
  confirmed_by: day < 3 ? undefined : 'Nurse Smith',
  confirmed_at: day < 3 ? undefined : new Date(Date.now() - (30 - day) * 24 * 60 * 60 * 1000).toISOString(),
}))

export const mockHistoryRecords: HistoryRecord[] = [
  {
    id: 1,
    station_id: 1,
    item_id: 1,
    quantity_used_total: 150,
    quantity_remaining: 350,
    cost_value: 175,
    income_value: 180,
    profit_margin: 2.86,
    month: '2024-05',
    generated_at: new Date().toISOString(),
  },
  {
    id: 2,
    station_id: 1,
    item_id: 2,
    quantity_used_total: 100,
    quantity_remaining: 200,
    cost_value: 80,
    income_value: 200,
    profit_margin: 60.0,
    month: '2024-05',
    generated_at: new Date().toISOString(),
  },
]
